import AutoSamplingTheory.TechnicalLemmas.Analysis.Calculus
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexAEDifferentiable
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexSubgradient
import AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicCostExpectation
import AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost
import AutoSamplingTheory.TechnicalLemmas.Analysis.Integrability
import AutoSamplingTheory.TechnicalLemmas.Analysis.LeftLebesgueAverage
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCyclicMonotonicity
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCycleNeighborhood
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCycleQuantitativeNeighborhood
import AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost
import AutoSamplingTheory.TechnicalLemmas.Analysis.PrefixIntegral

/-!
# Analysis technical lemma arsenal

Parent import surface for reusable analysis lemmas.
-/
