import AutoSamplingTheory.TechnicalLemmas.Analysis.Calculus
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexAEDifferentiable
import AutoSamplingTheory.TechnicalLemmas.Analysis.Integrability
import AutoSamplingTheory.TechnicalLemmas.Analysis.LeftLebesgueAverage
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCyclicMonotonicity
import AutoSamplingTheory.TechnicalLemmas.Analysis.PrefixIntegral
import AutoSamplingTheory.TechnicalLemmas.Analysis.RockafellarFiniteChain

/-!
# Analysis technical lemma arsenal

Parent import surface for reusable analysis lemmas.
-/
