import AutoSamplingTheory.TechnicalLemmas.Analysis.BoundedQuadraticCostIntegrability

#check AutoSamplingTheory.TechnicalLemmas.Analysis.BoundedQuadraticCostIntegrability.norm_sub_lt_center_distance_add_two_radius
#check AutoSamplingTheory.TechnicalLemmas.Analysis.BoundedQuadraticCostIntegrability.integrable_norm_sub_sq_of_prob_one_bounded_rectangle
#check AutoSamplingTheory.TechnicalLemmas.Analysis.BoundedQuadraticCostIntegrability.integrable_cross_norm_sub_sq_of_prob_one_bounded_rectangles
