import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationGridL2

#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationGridL2.integral_centeredSquaredIncrement_mul_eq_zero
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationGridL2.integral_quadraticVariationError_sq_eq_sum
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationGridL2.integral_quadraticVariationError_sq_eq_two_mul_sum_cellLength_sq
