import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation

/-!
Focused ABI checks for the first B19.2 quadratic-variation packet.
-/

#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.increment_memLp_two
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.increment_sq_integrable
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.integral_centered_increment_sq_eq_zero
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.centeredSquaredIncrement
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.quadraticVariationError
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.integral_quadraticVariationError_eq_zero
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariation.integral_quadraticVariationSum_eq_sum_cellLengths
