import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationL2

#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationL2.integral_increment_pow_four_nndist
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationL2.integral_increment_pow_four
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationL2.centered_increment_sq_memLp_two
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.BrownianQuadraticVariationL2.integral_centered_increment_sq_sq
