import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher.DirichletPairDomain
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher.HasCanonicalFisherGamma
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher.dirichletForm_density_logRatio_eq_information
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher.dirichletForm_density_logRatio_eq_integral_scoreSq
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher.hasDerivAt_eq_neg_information_of_eq_neg_dirichlet
