import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.CanonicalLocalizationTheorem

namespace AutoSamplingTheory.Tests.CanonicalLocalizationTheorem

open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.CanonicalLocalizationTheorem

#check canonicalStoppedProgressiveL2
#check canonicalStoppedProgressiveL2_process
#check chewi_proposition_1_1_13

end AutoSamplingTheory.Tests.CanonicalLocalizationTheorem
