import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalKLDissipation

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalKLDissipation.FlowDerivativeDomain
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalKLDissipation.kl_hasDerivAt_integral_rhoDot_mul_logRatio
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalKLDissipation.kl_hasDerivAt_eq_neg_dirichletForm
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalKLDissipation.kl_hasDerivAt_eq_neg_information
