import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.scoreSq
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.SmoothFiniteScoreDomain
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.information
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.information_eq_relativeFisher
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.information_eq_integral_scoreSq
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.information_eq_integral_density_mul_scoreSq
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.scoreSq_integrable
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.information_nonneg
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher.information_proof_irrel
