import AutoSamplingTheory.TechnicalLemmas.Measure.CanonicalGlobalCompetitor

#check AutoSamplingTheory.TechnicalLemmas.Measure.CanonicalGlobalCompetitor.canonicalGlobalCompetitor
#check AutoSamplingTheory.TechnicalLemmas.Measure.CanonicalGlobalCompetitor.commonSliceRemoved_toMeasure_le_ambient
#check AutoSamplingTheory.TechnicalLemmas.Measure.CanonicalGlobalCompetitor.ambient_eq_remainder_add_commonSliceRemoved
#check AutoSamplingTheory.TechnicalLemmas.Measure.CanonicalGlobalCompetitor.canonicalGlobalCompetitor_preserves_marginals
