import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.GlobalItoProcessProgressive
import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.ProgressiveDriftIntegral
import Mathlib.Analysis.InnerProductSpace.PiL2

open MeasureTheory
open scoped NNReal RealInnerProductSpace BigOperators

#check MeasureTheory.IsStronglyProgressive.add
#check MeasureTheory.IsStronglyProgressive.finsetSum
#check MeasureTheory.StronglyAdapted.isStronglyProgressive_of_continuous
#check measurable_pi_lambda
#check measurable_pi_iff
#check Measurable.stronglyMeasurable
#check WithLp.linearEquiv
#check WithLp.toLp
#check WithLp.ofLp
