import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.ChewiDefinition1_1_17

namespace AutoSamplingTheory.Tests.ChewiDefinition1_1_17

open MeasureTheory
open scoped NNReal RealInnerProductSpace

#check TechnicalLemmas.StochasticProcesses.ChewiDefinition1_1_17.stochasticIntegral
#check TechnicalLemmas.StochasticProcesses.ChewiDefinition1_1_17.stochasticIntegral_coordinate
#check TechnicalLemmas.StochasticProcesses.ChewiDefinition1_1_17.drift_integral_coordinate
#check TechnicalLemmas.StochasticProcesses.ChewiDefinition1_1_17.definition_1_1_17_vector_display
#check TechnicalLemmas.StochasticProcesses.ChewiDefinition1_1_17.chewi_definition_1_1_17

end AutoSamplingTheory.Tests.ChewiDefinition1_1_17
