import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CommonReferenceRNRealDensity

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.CommonReferenceRNRealDensity.density_withDensity_eq_toReal_div
