import AutoSamplingTheory.TechnicalLemmas.Measure.CommonSlicePermutationReplacement

#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonSlicePermutationReplacement.commonSliceRemoved
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonSlicePermutationReplacement.commonSlicePermutationReplacement
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonSlicePermutationReplacement.commonSlicePermutationReplacement_map_fst
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonSlicePermutationReplacement.commonSlicePermutationReplacement_map_snd
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonSlicePermutationReplacement.commonSlicePermutationReplacement_preserves_removed_marginals
