import AutoSamplingTheory.TechnicalLemmas.Measure.CommonNoiseContraction

#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonNoiseContraction.addNoise
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonNoiseContraction.synchronousNoiseCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonNoiseContraction.isCoupling_synchronousNoiseCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonNoiseContraction.lintegral_quadraticCost_synchronousNoiseCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CommonNoiseContraction.wassersteinDistance_addNoise_le
