import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.CompletedEnergy

namespace AutoSamplingTheory.Tests.CompletedEnergy

open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.CompletedEnergy

#check badEnergySet
#check measure_badEnergySet_zero
#check measurableSet_badEnergySet
#check completedEnergy
#check completedEnergy_stronglyMeasurable
#check continuous_completedEnergy
#check monotone_completedEnergy
#check completedEnergy_zero
#check completedEnergy_nonneg
#check completedEnergy_eq_terminal_of_le
#check measurableSet_completedEnergy_ge

end AutoSamplingTheory.Tests.CompletedEnergy
