import AutoSamplingTheory.TechnicalLemmas.Measure.CouplingQuadraticIntegrability

#check AutoSamplingTheory.TechnicalLemmas.Measure.CouplingQuadraticIntegrability.measurePreserving_fst_of_isCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CouplingQuadraticIntegrability.measurePreserving_snd_of_isCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CouplingQuadraticIntegrability.integrable_norm_sq_fst_of_isCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CouplingQuadraticIntegrability.integrable_norm_sq_snd_of_isCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.CouplingQuadraticIntegrability.integrable_norm_sub_sq_of_isCoupling
