import AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost

#check AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost.cycleSuccessorPerm
#check AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost.cycleSuccessorPerm_apply
#check AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost.permutedPairingGap_cycleSuccessor_eq_cycleValue
#check AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost.diagonal_sub_cyclicCost_eq_two_cycleValue
#check AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost.cyclicQuadraticCost_lt_of_cycleValue_pos
