import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.DiscreteDoobL2

open AutoSamplingTheory TechnicalLemmas StochasticProcesses

#check DiscreteDoobL2.runningAbsMax
#check DiscreteDoobL2.sampledFiltration
#check DiscreteDoobL2.Martingale.sampled
#check DiscreteDoobL2.doobL2_finite
#check DiscreteDoobL2.doobL2_finite_sq
#check DiscreteDoobL2.doobL2_sampled
