import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos.toMatrix_affineDisplacementDerivative_posDef
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos.toMatrix_affineDisplacementDerivative_posDef_of_posSemidef
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos.det_affineDisplacementDerivative_pos
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos.det_affineDisplacementDerivative_pos_of_posSemidef
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos.abs_det_affineDisplacementDerivative_eq
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementDerivativeDetPos.abs_det_affineDisplacementDerivative_eq_of_posSemidef
