import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialMarginals

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialMarginals.integral_fst_eq_of_isCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialMarginals.integral_snd_eq_of_isCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialMarginals.integral_endpoint_affine_potential_eq
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialMarginals.integral_potential_displacementInterpolation_le_marginals
