import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapDerivative

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapDerivative.affineDisplacementMap
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapDerivative.affineDisplacementDerivative
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapDerivative.hasFDerivAt_affineDisplacementMap
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapDerivative.hasFDerivWithinAt_affineDisplacementMap
