import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialEnergy

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialEnergy.potential_pointMap_le
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialEnergy.integral_potential_pointMap_le
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialEnergy.integral_displacementInterpolation_eq_integral_pointMap
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPotentialEnergy.integral_potential_displacementInterpolation_le
