import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapInjectivity

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapInjectivity.IsMonotoneMap
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapInjectivity.inner_affineDisplacementMap_sub
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapInjectivity.affineDisplacementMap_inner_lower_bound
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementMapInjectivity.injective_affineDisplacementMap_of_monotone
