import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementConvexGradientPositive

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementConvexGradientPositive.isPositive_fderiv_of_convex_gradient_field
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementConvexGradientPositive.toMatrix_fderiv_posSemidef_of_convex_gradient_field
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementConvexGradientPositive.det_affineDisplacementDerivative_pos_of_convex_gradient_field
