import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementSupportingPotential

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementSupportingPotential.IsSupportingField
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementSupportingPotential.isMonotoneMap_of_isSupportingField
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementSupportingPotential.injective_affineDisplacementMap_of_supportingField
