import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPositiveOperator

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPositiveOperator.toMatrix_posSemidef_of_isPositive
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPositiveOperator.det_affineDisplacementDerivative_pos_of_isPositive
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPositiveOperator.abs_det_affineDisplacementDerivative_eq_of_isPositive
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementPositiveOperator.integral_image_affineDisplacementMap_eq_integral_det_smul_of_isPositive
