import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.DyadicGlobalHorizon

namespace AutoSamplingTheory.Tests.DyadicGlobalHorizon

open MeasureTheory
open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses
open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.DyadicGlobalHorizon
open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.GlobalLocalProgressiveL2
open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.ProgressiveL2
open scoped NNReal Topology

#check dyadicGlobalIndex
#check dyadicHorizon
#check dyadicGlobalIndex_add_one
#check integerHorizon_dyadicGlobalIndex
#check dyadicGlobalIndex_mono
#check tendsto_dyadicGlobalIndex_atTop
#check dyadicGlobalLocalizingTime
#check dyadicGlobalLocalizingTime_isChewiStoppingTime
#check dyadicGlobalLocalizingTime_mono
#check dyadicGlobalLocalizingTime_le_horizon
#check dyadicGlobalLocalizingTime_tendsto_top_ae

end AutoSamplingTheory.Tests.DyadicGlobalHorizon
