import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.ElementaryItoAlgebra

namespace AutoSamplingTheory.Tests.ElementaryItoAlgebra

open TechnicalLemmas.StochasticProcesses
open ElementaryItoIntegral ElementaryItoAlgebra

#check ElementaryItoAlgebra.zeroLike
#check ElementaryItoAlgebra.neg
#check ElementaryItoAlgebra.smul
#check ElementaryItoAlgebra.add
#check ElementaryItoAlgebra.sub
#check ElementaryItoAlgebra.add_value
#check ElementaryItoAlgebra.sub_value
#check ElementaryItoAlgebra.elementaryItoIntegral_add
#check ElementaryItoAlgebra.elementaryItoIntegral_sub

end AutoSamplingTheory.Tests.ElementaryItoAlgebra
