import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.EnergyStoppedIntegrand

namespace AutoSamplingTheory.Tests.EnergyStoppedIntegrand

open AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.EnergyStoppedIntegrand

#check energyStoppedIntegrand
#check energyStoppedIntegrand_stronglyProgressive
#check completedEnergy_lt_iff_lt_canonicalEnergyLocalizer
#check sectionSquare_integrable
#check integral_energyStoppedIntegrand_sq
#check integral_energyStoppedIntegrand_sq_le

end AutoSamplingTheory.Tests.EnergyStoppedIntegrand
