import AutoSamplingTheory.TechnicalLemmas.InformationTheory.FiniteACFDivergenceCommonReference

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.FiniteACFDivergenceCommonReference.value_withDensity_eq_integral_mul_of_density_ae
