import AutoSamplingTheory.TechnicalLemmas.InformationTheory.GeodesicFisherTransport

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.GeodesicFisherTransport.value_le_neg_directionalDerivative
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.GeodesicFisherTransport.sq_le_fisher_mul_sq_of_le_sqrt_mul
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.GeodesicFisherTransport.sq_le_fisher_mul_dist_sq_of_geodesic_first_order
