import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.LaggedDyadicConvergence

open AutoSamplingTheory TechnicalLemmas StochasticProcesses

#check LaggedDyadicConvergence.abs_laggedDyadicApprox_sub_le
#check LaggedDyadicConvergence.clippedHorizonFunction
#check LaggedDyadicConvergence.laggedDyadicApprox_tendsto_ae
#check LaggedDyadicConvergence.laggedDyadicApprox_abs_le
#check LaggedDyadicConvergence.abs_laggedDyadic_error_le_two_mul
#check LaggedDyadicConvergence.tendsto_integral_sq_laggedDyadicApprox_sub
#check LaggedDyadicConvergence.tendsto_laggedDyadicApprox_toLp_clipped
