import AutoSamplingTheory.TechnicalLemmas.Probability.NormalizedFiniteMeasureIntegral

#check AutoSamplingTheory.TechnicalLemmas.Probability.NormalizedFiniteMeasureIntegral.integral_eq_mass_mul_integral_normalize
#check AutoSamplingTheory.TechnicalLemmas.Probability.NormalizedFiniteMeasureIntegral.integral_lt_integral_iff_normalize_of_mass_pos
