import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarConvexDomain

#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarConvexDomain.chainValue_convexCombination
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarConvexDomain.properRockafellarPotential_combo_le
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarConvexDomain.properRockafellarPotential_combo_lt_top
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarConvexDomain.convex_effectiveDomain
