import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingClosedChainMonotonicity

#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingClosedChainMonotonicity.tuplePathValue
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingClosedChainMonotonicity.chainValue_ofFn_eq_tuplePathValue
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingClosedChainMonotonicity.chainValue_ofFn_at_first_eq_cycle_sum
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingClosedChainMonotonicity.chainValue_nonpos_of_nodup
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingClosedChainMonotonicity.pairingClosedChainMonotone_of_distinct
