import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarSupportGradient

#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarSupportGradient.eq_gradient_of_properSupportsAt_of_mem_interior
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PairingRockafellarSupportGradient.snd_eq_gradient_of_mem_of_mem_interior
