import AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost

#check AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost.diagonalQuadraticCost
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost.permutedQuadraticCost
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost.permutedPairingGap
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost.quadraticCostDifference_pointwise
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost.diagonal_sub_permuted_eq_two_pairingGap
#check AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost.permutedQuadraticCost_lt_of_pairingGap_pos
