import AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost

#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.realQuadraticCost
#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.crossQuadraticCost
#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.measurePreserving_commonMassProduct_source_target
#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.integral_marginal_commonMassProduct_eq_mass_mul_normalized_cross
#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.integral_sum_eq_mass_mul_diagonalProduct
#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.integral_permutedReplacement_symm_eq_mass_mul_permutedProduct
#check AutoSamplingTheory.TechnicalLemmas.Measure.PermutedReplacementQuadraticCost.integral_permutedReplacement_symm_lt_sum_of_productGap
