import AutoSamplingTheory.TechnicalLemmas.Measure.ProbabilityCouplingCompactness

#check AutoSamplingTheory.TechnicalLemmas.Measure.ProbabilityCouplingCompactness.IsProbabilityCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.ProbabilityCouplingCompactness.isProbabilityCoupling_iff_isCoupling_toMeasure
#check AutoSamplingTheory.TechnicalLemmas.Measure.ProbabilityCouplingCompactness.isClosed_probabilityCouplingSet
#check AutoSamplingTheory.TechnicalLemmas.Measure.ProbabilityCouplingCompactness.isTightMeasureSet_couplingSet
#check AutoSamplingTheory.TechnicalLemmas.Measure.ProbabilityCouplingCompactness.isCompact_probabilityCouplingSet
