import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.ProgressiveL2Density

open AutoSamplingTheory TechnicalLemmas StochasticProcesses

#check ProgressiveL2Density.fastTolerance
#check ProgressiveL2Density.summable_fastTolerance
#check ProgressiveL2Density.strictSelection
#check ProgressiveL2Density.strictMono_strictSelection
#check ProgressiveL2Density.truncationIndex
#check ProgressiveL2Density.dyadicLevel
#check ProgressiveL2Density.DyadicElementaryProcess
#check ProgressiveL2Density.canonicalElementaryApprox
#check ProgressiveL2Density.progressiveL2_elementary_dense
