import AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalBrenierMap

#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalBrenierMap.ae_snd_eq_gradient_of_quadraticOptimal_of_base
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalBrenierMap.map_gradient_eq_of_quadraticOptimal_of_base
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalBrenierMap.exists_base_map_gradient_eq_of_quadraticOptimal
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalBrenierMap.exists_base_map_gradient_eq_of_quadraticOptimal_p2ac
