import AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalMapUniqueness

#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalMapUniqueness.HasUniqueQuadraticOptimalCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalMapUniqueness.ae_eq_of_quadraticOptimalMap_of_uniqueCoupling
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalMapUniqueness.ae_eq_of_quadraticOptimalMap_of_forall_optimal_eq
