import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh

#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.sum_sq_le_mesh_mul_sum
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.sum_sq_le_mesh_mul_total
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.two_mul_sum_sq_le_two_mul_mesh_mul_total
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.dyadic_cellCount_mul_mesh
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.dyadic_cellLength_eq_mesh
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.dyadic_sum_cellLength_eq_total
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.QuadraticVariationMesh.dyadic_two_mul_sum_cellLength_sq_le
