import AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalSupportCyclic

#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalSupportCyclic.pairingDistinctCycleMonotone_support_of_quadraticOptimal_finite
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalSupportCyclic.pairingDistinctCycleMonotone_support_of_quadraticOptimal
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalSupportCyclic.pairingDistinctCycleMonotone_support_of_quadraticOptimal_p2ac
