import AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher.densityEnergy
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher.information
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher.densityEnergy_nonneg
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher.densityEnergy_eq_zero_of_gradient_eq_zero
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher.information_eq_zero_of_gradient_ae_eq_zero
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher.information_congr_gradient_ae
