import AutoSamplingTheory.TechnicalLemmas.Analysis.RockafellarRootProper

#check AutoSamplingTheory.TechnicalLemmas.Analysis.RockafellarRootProper.isGreatest_zero_rockafellarValueSet_at_root
#check AutoSamplingTheory.TechnicalLemmas.Analysis.RockafellarRootProper.properRockafellarPotential_at_root_eq_zero
#check AutoSamplingTheory.TechnicalLemmas.Analysis.RockafellarRootProper.root_mem_effectiveDomain_properRockafellarPotential
