import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceDissipation

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceDissipation.WeakFPDissipationDomain
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceDissipation.spatial_pairing_eq_dissipation_ae
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceDissipation.hasDerivAt_eq_neg_diffusionScale_mul_dissipation
