import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceWeakAdjoint

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceWeakAdjoint.generator_referenceObservable_apply
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceWeakAdjoint.integral_derivativeIntegrand_eq_generator_pairings
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceWeakAdjoint.integral_derivativeIntegrand_eq_source_generator_pairings
