import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradientIdentities

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradientIdentities.hasDerivAt_f_sub_mul_fPrime
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradientIdentities.hasGradientAt_density_product
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradientIdentities.hasGradientAt_fPrime_comp
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradientIdentities.hasGradientAt_f_sub_rho_mul_fPrime
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradientIdentities.source_gradient_packet
