import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGeneratorCancellation

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGeneratorCancellation.generator_terms_eq_neg_fSecond_mul_carreDuChamp
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGeneratorCancellation.generator_terms_eq_neg_fSecond_mul_carreDuChamp_of_rho_mul
