import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradient

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradient.common_diffusion_pairing_eq
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradient.common_diffusion_pairing_eq_of_gradients
