import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergence

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergence.hasDerivAt_weighted_f_divergence_integrand
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergence.hasDerivAt_weighted_f_divergence_integrand_of_ratio
