import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceAbstract

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceAbstract.factorized_source_pointwise_cancellation
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceAbstract.source_pointwise_cancellation
