import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceIntegral

#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceIntegral.derivativeIntegrand
#check AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceIntegral.hasDerivAt_integral_weighted_f_divergence_of_dominated
