import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GradientArcMean

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GradientArcMean.gradient_arc_mean
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GradientArcMean.gradient_arc_mean
