import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.PoissonQueryTail

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.PoissonQueryTail.poisson_query_tail
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.PoissonQueryTail.poisson_query_tail
