import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.IdealRGOIdentification

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.IdealRGOIdentification.ideal_rgo_identification
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.IdealRGOIdentification.ideal_rgo_identification
