import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TerminalFORSKernel

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TerminalFORSKernel.terminal_fors_kernel
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TerminalFORSKernel.terminal_fors_kernel
