import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedMeanExponential

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedMeanExponential.clipped_mean_exponential
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedMeanExponential.clipped_mean_exponential
