import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianArcLaw

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianArcLaw.gaussian_arc_law
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianArcLaw.gaussian_arc_law
