import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ObservationConditionalKernel

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ObservationConditionalKernel.observation_conditional_kernel
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ObservationConditionalKernel.observation_conditional_kernel
