import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedGradientProgram

#check AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedGradientProgram.clipped_gradient_program
#print axioms AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedGradientProgram.clipped_gradient_program
