import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceIntegral
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceSpatial
import Mathlib.Tactic

/-!
# Weak-Fokker--Planck join for simultaneous f-divergence dissipation

This file is the algebraic/analytic join immediately below Chewi Theorem 8.3.1.
The time-differentiation node and the pointwise spatial-calculus node are
already separate.  Here we assume only the two weak integration-by-parts
identities supplied by a common diffusion and combine them into the final
weighted Fisher-type dissipation integral.

Nothing in this file proves a Fokker--Planck equation, whole-space boundary
decay, cutoff convergence, positivity of densities, or dominated
differentiation.  Those obligations remain explicit upstream nodes.
-/

namespace AutoSamplingTheory
namespace TechnicalLemmas
namespace InformationTheory
namespace SimultaneousFDivergenceDissipation

open MeasureTheory
open scoped RealInnerProductSpace

noncomputable section

/-- Density ratio at the selected time.  Nonvanishing/positivity of the
reference density is deliberately not hidden in this definition. -/
def rhoAt
    {E : Type*} (p q : ℝ → E → ℝ) (s0 : ℝ) (x : E) : ℝ :=
  p s0 x / q s0 x

/-- The `p` contribution in the differentiated simultaneous f-divergence. -/
def pTimeTerm
    {E : Type*}
    (p q pDot : ℝ → E → ℝ) (fPrime : ℝ → ℝ) (s0 : ℝ) (x : E) : ℝ :=
  fPrime (rhoAt p q s0 x) * pDot s0 x

/-- The `q` contribution in the differentiated simultaneous f-divergence. -/
def qTimeTerm
    {E : Type*}
    (p q qDot : ℝ → E → ℝ) (f fPrime : ℝ → ℝ) (s0 : ℝ) (x : E) : ℝ :=
  let rho := rhoAt p q s0 x
  (f rho - rho * fPrime rho) * qDot s0 x

/-- Spatial pairing generated by the weak Fokker--Planck identity for the
numerator density `p = q rho`.

Mathlib's total `gradient` uses the Riesz representation of the derivative, so
completeness belongs at this definition rather than being left to downstream
consumers. -/
def pSpatialPairing
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (p q : ℝ → E → ℝ) (fPrime : ℝ → ℝ) (s0 : ℝ) (x : E) : ℝ :=
  let rho := rhoAt p q s0
  inner ℝ
    (gradient (fun y => fPrime (rho y)) x)
    (gradient (fun y => q s0 y * rho y) x)

/-- Spatial pairing generated by the weak Fokker--Planck identity for the
reference density. -/
def qSpatialPairing
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (p q : ℝ → E → ℝ) (f fPrime : ℝ → ℝ) (s0 : ℝ) (x : E) : ℝ :=
  let rho := rhoAt p q s0
  inner ℝ
    (gradient (fun y => f (rho y) - rho y * fPrime (rho y)) x)
    (gradient (q s0) x)

/-- The weighted Fisher-type integrand in Chewi Theorem 8.3.1. -/
def dissipationIntegrand
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (p q : ℝ → E → ℝ) (fSecond : ℝ → ℝ) (s0 : ℝ) (x : E) : ℝ :=
  let rho := rhoAt p q s0
  q s0 x * fSecond (rho x) * ‖gradient rho x‖ ^ 2

/-- Explicit selected-time contract between the dominated time derivative and
the two weak common-diffusion Fokker--Planck identities.

The weak identities are exactly the pieces later supplied by whole-space
integration by parts.  They are not inferred from a PDE here. -/
structure WeakFPDissipationDomain
    {E : Type*} [MeasurableSpace E] [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] [CompleteSpace E]
    (mu : Measure E)
    (p q pDot qDot : ℝ → E → ℝ)
    (f fPrime fSecond : ℝ → ℝ)
    (s0 diffusionScale : ℝ) : Prop where
  p_time_integrable : Integrable (pTimeTerm p q pDot fPrime s0) mu
  q_time_integrable : Integrable (qTimeTerm p q qDot f fPrime s0) mu
  p_pairing_integrable : Integrable (pSpatialPairing p q fPrime s0) mu
  q_pairing_integrable : Integrable (qSpatialPairing p q f fPrime s0) mu
  p_weak_fp :
    (∫ x, pTimeTerm p q pDot fPrime s0 x ∂mu) =
      -diffusionScale * ∫ x, pSpatialPairing p q fPrime s0 x ∂mu
  q_weak_fp :
    (∫ x, qTimeTerm p q qDot f fPrime s0 x ∂mu) =
      -diffusionScale * ∫ x, qSpatialPairing p q f fPrime s0 x ∂mu
  q_differentiable_ae : ∀ᵐ x ∂mu, DifferentiableAt ℝ (q s0) x
  rho_differentiable_ae :
    ∀ᵐ x ∂mu, DifferentiableAt ℝ (rhoAt p q s0) x
  f_hasDeriv :
    ∀ r : ℝ, HasDerivAt f (fPrime r) r
  fPrime_hasDeriv :
    ∀ r : ℝ, HasDerivAt fPrime (fSecond r) r

/-- Pointwise spatial pairing cancellation from the explicit differentiability
part of `WeakFPDissipationDomain`. -/
theorem spatial_pairing_eq_dissipation_ae
    {E : Type*} [MeasurableSpace E] [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] [CompleteSpace E]
    (mu : Measure E)
    (p q pDot qDot : ℝ → E → ℝ)
    (f fPrime fSecond : ℝ → ℝ)
    (s0 diffusionScale : ℝ)
    (h : WeakFPDissipationDomain mu p q pDot qDot f fPrime fSecond s0 diffusionScale) :
    ∀ᵐ x ∂mu,
      pSpatialPairing p q fPrime s0 x +
          qSpatialPairing p q f fPrime s0 x =
        dissipationIntegrand p q fSecond s0 x := by
  filter_upwards [h.q_differentiable_ae, h.rho_differentiable_ae] with x hq hrho
  unfold pSpatialPairing qSpatialPairing dissipationIntegrand
  exact
    SimultaneousFDivergenceSpatial.common_diffusion_pairing_source
      hq.hasGradientAt hrho.hasGradientAt
      (h.f_hasDeriv (rhoAt p q s0 x))
      (h.fPrime_hasDeriv (rhoAt p q s0 x))

/-- Weak common-diffusion dissipation join.

A supplied dominated derivative of the actual simultaneous f-divergence curve,
together with the two weak Fokker--Planck integration-by-parts identities,
yields

`D_f' = - diffusionScale * ∫ q f''(rho) ||grad rho||^2`.

For Chewi's heat normalization the later source-facing specialization sets the
appropriate diffusion scale; this theorem itself stays normalization-agnostic. -/
theorem hasDerivAt_eq_neg_diffusionScale_mul_dissipation
    {E : Type*} [MeasurableSpace E] [NormedAddCommGroup E]
    [InnerProductSpace ℝ E] [CompleteSpace E]
    (mu : Measure E)
    (p q pDot qDot : ℝ → E → ℝ)
    (f fPrime fSecond : ℝ → ℝ)
    (s0 diffusionScale : ℝ)
    (h : WeakFPDissipationDomain mu p q pDot qDot f fPrime fSecond s0 diffusionScale)
    (hTime :
      HasDerivAt
        (fun s => ∫ x, q s x * f (p s x / q s x) ∂mu)
        (∫ x,
          SimultaneousFDivergenceIntegral.derivativeIntegrand
            p q pDot qDot f fPrime s0 x ∂mu) s0) :
    HasDerivAt
      (fun s => ∫ x, q s x * f (p s x / q s x) ∂mu)
      (-diffusionScale *
        ∫ x, dissipationIntegrand p q fSecond s0 x ∂mu) s0 := by
  have htime_split :
      (∫ x,
          SimultaneousFDivergenceIntegral.derivativeIntegrand
            p q pDot qDot f fPrime s0 x ∂mu) =
        (∫ x, pTimeTerm p q pDot fPrime s0 x ∂mu) +
          ∫ x, qTimeTerm p q qDot f fPrime s0 x ∂mu := by
    rw [← integral_add h.p_time_integrable h.q_time_integrable]
    apply integral_congr_ae
    filter_upwards with x
    rfl
  have hpair_split :
      (∫ x, pSpatialPairing p q fPrime s0 x ∂mu) +
          ∫ x, qSpatialPairing p q f fPrime s0 x ∂mu =
        ∫ x, dissipationIntegrand p q fSecond s0 x ∂mu := by
    rw [← integral_add h.p_pairing_integrable h.q_pairing_integrable]
    exact integral_congr_ae
      (spatial_pairing_eq_dissipation_ae
        mu p q pDot qDot f fPrime fSecond s0 diffusionScale h)
  have hcoeff :
      (∫ x,
          SimultaneousFDivergenceIntegral.derivativeIntegrand
            p q pDot qDot f fPrime s0 x ∂mu) =
        -diffusionScale *
          ∫ x, dissipationIntegrand p q fSecond s0 x ∂mu := by
    calc
      (∫ x,
          SimultaneousFDivergenceIntegral.derivativeIntegrand
            p q pDot qDot f fPrime s0 x ∂mu) =
        (∫ x, pTimeTerm p q pDot fPrime s0 x ∂mu) +
          ∫ x, qTimeTerm p q qDot f fPrime s0 x ∂mu := htime_split
      _ = (-diffusionScale * ∫ x, pSpatialPairing p q fPrime s0 x ∂mu) +
          (-diffusionScale * ∫ x, qSpatialPairing p q f fPrime s0 x ∂mu) := by
            rw [h.p_weak_fp, h.q_weak_fp]
      _ = -diffusionScale *
          ((∫ x, pSpatialPairing p q fPrime s0 x ∂mu) +
            ∫ x, qSpatialPairing p q f fPrime s0 x ∂mu) := by ring
      _ = -diffusionScale *
          ∫ x, dissipationIntegrand p q fSecond s0 x ∂mu := by rw [hpair_split]
  rw [hcoeff] at hTime
  exact hTime

end

end SimultaneousFDivergenceDissipation
end InformationTheory
end TechnicalLemmas
end AutoSamplingTheory
