import AutoSamplingTheory.ExampleCases.SampleWiki
import AutoSamplingTheory.ExampleCases.ProximalBPS.GaussianReflection
import AutoSamplingTheory.ExampleCases.ProximalBPS.GaussianAugmentation
import AutoSamplingTheory.ExampleCases.ProximalBPS.GibbsAugmentation
import AutoSamplingTheory.ExampleCases.ProximalBPS.ReflectionL2
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalScore
import AutoSamplingTheory.ExampleCases.ProximalBPS.MacroscopicRepresentative
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalScoreDomain
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalBochner
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalGradient
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalResolvent
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RecursiveCondition
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RGOClosure
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RGOCalculus
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RecursiveVariance
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RecursiveDepth
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.LogarithmicDepth
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.Truncation
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianPowerMoment

/-!
# ASTIS example cases

This namespace is the public Lean entry point for externally sourced worked
examples that ASTIS turns into source-pinned theorem targets and then absorbs
into the reusable sampling-theory dependency graph.
-/
